name: Java Hello World CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build Java Hello World application
        run: |
          echo "public class Main { public static void main(String[] args) { System.out.println(\"Hello, World!\"); } }" > Main.java
          javac Main.java

      - name: Build and Dockerize with Jib
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.1:build -Dimage=public.ecr.aws/u1u3e1y1/github-actions/javahelloworld:v1


      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA4MTWIBZZVZI5H67E
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Push Docker image to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u1u3e1y1
          docker push public.ecr.aws/u1u3e1y1/github-actions:latest

      - name: Deploy application with kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f path-to-your-deployment.yaml
